swagger: "2.0"
info:
  version: "0.0.1"
  title: coffee-api
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /sponsors:
    x-swagger-router-controller: sponsors
    get:
      description: Returns all sponsors
      operationId: getSponsors
      responses:
        "200":
          description: Success
          schema:
            title: List of active sponsors
            type: array
            items:
              $ref: "#/definitions/Sponsor"
        default:
          description: Error
          schema:
            description: Error message
            type: string
    post:
      description: Create new sponsor
      operationId: createSponsor
      parameters:
        - in: body
          name: body
          description: Sponsor object
          required: true
          schema:
            $ref: "#/definitions/Sponsor"
      responses:
        "201":
          description: Success
          schema:
            description: Success message
            type: string
        default:
          description: Error
          schema:
            description: Error message
            type: string
  /sponsors/{sponsorID}:
    x-swagger-router-controller: sponsors
    get:
      description: Returns all info for one sponsor
      operationId: getSponsor
      parameters:
        - in: path
          name: sponsorID
          description: ID of sponsor
          required: true
          type: string
          format: uuid
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Sponsor"
        default:
          description: Error
          schema:
            description: Error message
            type: string
  /beans:
    x-swagger-router-controller: beans
    post:
      description: Create new bean
      operationId: createBean
      parameters:
        - in: body
          name: body
          description: Bean object
          required: true
          schema:
            $ref: "#/definitions/Bean"
      responses:
        "201":
          description: Success
          schema:
            description: Success message
            type: string
        default:
          description: Error
          schema:
            description: Error message
            type: string
  /recipes:
    x-swagger-router-controller: recipes
    post:
      description: Create new recipe
      operationId: createRecipe
      parameters:
        - in: body
          name: body
          description: Recipe object
          required: true
          schema:
            $ref: "#/definitions/Recipe"
      responses:
        "201":
          description: Success
          schema:
            description: Success message
            type: string
        default:
          description: Error
          schema:
            description: Error message
            type: string
    get:
      description: Returns all default recipes
      operationId: getDefaultRecipes
      responses:
        "200":
          description: Success
          schema:
            title: List of default recipes
            type: array
            items:
              $ref: "#/definitions/Recipe"
        default:
          description: Error
          schema:
            description: Error message
            type: string
  /swagger:
    x-swagger-pipe: swagger_raw

definitions:
  Sponsor:
    required:
      - company
      - location
      - description
      - status
    properties:
      sponsor_id:
        type: string
        format: uuid
      image_link:
        type: string
      company:
        type: string
      location:
        type: string
      street_address:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      description:
        type: string
      theme_color:
        type: string
      text_color:
        type: string
      beans:
        type: array
        items:
          $ref: "#/definitions/Bean"
      recipes:
        type: array
        items:
          $ref: "#/definitions/Recipe"
      status:
        type: string
        enum: ["ACTIVE", "INACTIVE"]
  Bean:
    required:
      - sponsor_id
      - title
      - description
      - status
    properties:
      bean_id:
        type: string
        format: uuid
      sponsor_id:
        type: string
        format: uuid
      title:
        type: string
      description:
        type: string
      bean_link:
        type: string
      status:
        type: string
        enum: ["ACTIVE", "INACTIVE"]
  Recipe:
    required:
      - brewing_vessel
      - vessel_id
      - filter_type
      - orientation
      - recipe_name
      - total_coffee
      - grind_size
      - total_water
      - water_temp
      - steps
      - status
    properties:
      recipe_id:
        type: string
        format: uuid
      sponsor_id:
        type: string
        format: uuid
      brewing_vessel:
        type: string
      vessel_id:
        type: string
      filter_type:
        type: string
      orientation:
        type: string
      recipe_name:
        type: string
      total_coffee:
        type: string
      grind_size:
        type: string
      total_water:
        type: string
      water_temp:
        type: string
      steps:
        type: array
        items:
          $ref: "#/definitions/Step"
      status:
        type: string
        enum: ["ACTIVE", "INACTIVE"]
      favorited:
        type: boolean
      default:
        type: boolean
  Step:
    required:
      - title
      - type
    properties:
      step_id:
        type: string
        format: uuid
      title:
        type: string
      type:
        type: string
      properties:
        type: object
